steps:
  # تحميل القيم من ملف .env وتسجيل الدخول إلى Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export $(grep -v '^#' .env | xargs) && \
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  # بناء صورة Django
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '3booda24/devops-project-django_web:latest'
      - '.'
    dir: '.'

  # بناء صورة nginx
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '3booda24/devops-project-django_nginx:latest'
      - '.'
    dir: 'nginx'

  # دفع صورة Django
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '3booda24/devops-project-django_web:latest'

  # دفع صورة nginx
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '3booda24/devops-project-django_nginx:latest'

  # تطبيق ملفات Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - --validate=false
      - -f
      - .
      - -f
      - ./deploy
      - -n
      - prod
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=django

options:
  logging: CLOUD_LOGGING_ONLY

