steps:
  # تسجيل الدخول إلى Docker Hub باستخدام Secret Manager
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    secretEnv:
      - DOCKERHUB_USERNAME
      - DOCKERHUB_PASSWORD

  # بناء صورة الـ web (Django)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '3booda24/devops-project-django_web:latest'
      - '.'
    dir: '.'

  # بناء صورة الـ nginx
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '3booda24/devops-project-django_nginx:latest'
      - '.'
    dir: 'nginx'

  # دفع صورة الـ web (Django)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '3booda24/devops-project-django_web:latest'

  # دفع صورة الـ nginx
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '3booda24/devops-project-django_nginx:latest'

  # تطبيق ملفات Kubernetes YAML في الجذر وداخل deploy
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - apply
      - --validate=false
      - -f
      - .
      - -f
      - ./deploy
      - -n
      - prod
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-c
      - CLOUDSDK_CONTAINER_CLUSTER=django

images:
  - '3booda24/devops-project-django_web:latest'
  - '3booda24/devops-project-django_nginx:latest'

secrets:
  - secretEnv:
      DOCKERHUB_USERNAME: projects/1024459810410/secrets/DOCKERHUB_USERNAME/versions/latest
      DOCKERHUB_PASSWORD: projects/1024459810410/secrets/DOCKERHUB_PASSWORD/versions/latest


