version: "3.8"
services:
  web:
    build:
      context: .
    container_name: django-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # حفظ الملفات الثابتة في مجلد مشترك
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - DB_HOST=db
      - DB_PORT=5432
      - STATIC_ROOT=/app/staticfiles  # إعداد STATIC_ROOT دون تعديل الكود
    depends_on:
      - db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles  # يستخدم نفس مجلد staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # ملف إعدادات NGINX

volumes:
  postgres_data:
  static_volume:

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  postgres_db:
    file: ./secrets/postgres_db

