apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: gcr.io/excellent-guide-445190-e0/nginx:7c6e40d9
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-volume
              mountPath: /app/staticfiles
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume-claim

