apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: prod
spec:
  replicas: 7
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 3booda24/devops-project-django_nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-volume
              mountPath: /app/staticfiles
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume-claim

